# An example using multi-stage image builds to create a final image without uv.

# First, build the application in the `/app` directory.
# See `Dockerfile` for details.
#FROM ghcr.io/astral-sh/uv:python3.10-bookworm-slim AS builder
FROM python:3.10.12-slim AS builder
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy
WORKDIR /app
RUN pip install uv

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev
ADD . /app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev


# Then, use a final image without uv
#FROM python:3.10-slim-bookworm
FROM python:3.10.12-slim
# It is important to use the image that matches the builder, as the path to the
# Python executable must be the same, e.g., using `python:3.11-slim-bookworm`
# will fail.

WORKDIR /app

# Copy the application from the builder
COPY --from=builder --chown=app:app /app /app

# Create a non-root user
RUN groupadd -r app && useradd -r -g app app

# Install the project and its dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    python -m pip install .

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

# Switch to non-root user
USER app

# Run the FastAPI application by default
CMD ["python", "/app/run.py"]
